language: go

os:
  - linux
  - osx
  - windows

go_import_path: toolman.org/time/timespan/v2

go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...
  - $GOPATH/bin/goveralls -service=travis-ci

